#!/usr/bin/env bash

# Update package repositories and install Nginx
apt-get update
apt-get install -y nginx

# Create index.html with "Hello World!"
echo "Hello World!" | tee /var/www/html/index.html

# Configure redirect for /redirect_me
string_for_replacement="server_name _;\\n\\trewrite ^\\/redirect_me https:\\/\\/www.youtube.com permanent;"
sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
service nginx restart
