#!/usr/bin/env bash

# Update package repositories and install Nginx
apt-get update
apt-get install -y nginx

# Create index.html with "Hello World!"
echo "Hello World!" | tee /var/www/html/index.html

# Configure redirect for /redirect_me
redirect_config="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sed -i "s/server_name _;/$redirect_config/" /etc/nginx/sites-enabled/default

# Create custom 404 error page
echo "Ceci n'est pas une page" | tee /var/www/html/404.html

# Configure Nginx to use custom 404 error page
error_config="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/listen 80 default_server;/$error_config/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
service nginx restart
