#!/usr/bin/env bash
#This Script runs nginx through nginx user

chmod 644 /etc/nginx/nginx.conf

# Replace the 'user' directive in /etc/nginx.conf with 'user nginx'
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf

# Modify the default Nginx configuration to listen on port 8080 instead of 80
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default


pkill apache2

# Switch to the 'nginx' user and restart the Nginx service
su nginx -s/bin/bash -c ' service nginx restart'

